/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TuringsMachin.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import TuringsMachin.logic.TuringsMachin;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class CalculatorView extends javax.swing.JFrame {
    private TuringsMachin machine = new TuringsMachin();
    private Timer timer = null;
    final int delay=250;
    String number1;
    String logicOperator;
    String number2;
    Boolean reboot = false;
    /**
     * Creates new form CalculadoraVista
     */
    public CalculatorView() {
        initComponents();
        tFScreen.setEditable(false);
        tAResultScreen.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tFScreen = new javax.swing.JTextField();
        b4 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        bEqual = new javax.swing.JButton();
        bDivision = new javax.swing.JButton();
        bPlus = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        bMultiplication = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        bMinus = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        bForward = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAResultScreen = new javax.swing.JTextArea();
        bReboot = new javax.swing.JButton();
        bClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tFScreen.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        tFScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFScreenActionPerformed(evt);
            }
        });

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/numero (3).png"))); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/numero (6).png"))); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        bEqual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/igual.png"))); // NOI18N
        bEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEqualActionPerformed(evt);
            }
        });

        bDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/division.png"))); // NOI18N
        bDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivisionActionPerformed(evt);
            }
        });

        bPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/mas.png"))); // NOI18N
        bPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlusActionPerformed(evt);
            }
        });

        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/numero (8).png"))); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/numero (9).png"))); // NOI18N
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/numero (7).png"))); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        bMultiplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/cerrar.png"))); // NOI18N
        bMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMultiplicationActionPerformed(evt);
            }
        });

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/numero.png"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/numero (4).png"))); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        bMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/menos.png"))); // NOI18N
        bMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMinusActionPerformed(evt);
            }
        });

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/numero (5).png"))); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/numero (2).png"))); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/numero (1).png"))); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        bForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/avance-rapido.png"))); // NOI18N
        bForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bForwardActionPerformed(evt);
            }
        });

        tAResultScreen.setColumns(20);
        tAResultScreen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tAResultScreen.setRows(5);
        jScrollPane1.setViewportView(tAResultScreen);

        bReboot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/refrescar.png"))); // NOI18N
        bReboot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRebootActionPerformed(evt);
            }
        });

        bClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TuringsMachin/img/anterior.png"))); // NOI18N
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bForward, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(b5))
                            .addComponent(bReboot))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bPlus))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(b9)
                                    .addGap(18, 18, 18)
                                    .addComponent(bDivision))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bMultiplication))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b3)
                                        .addGap(18, 18, 18)
                                        .addComponent(bMinus))))))
                    .addComponent(tFScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tFScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b9)
                        .addComponent(bDivision))
                    .addComponent(b7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b4)
                        .addGap(18, 18, 18)
                        .addComponent(b1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b5)
                        .addGap(18, 18, 18)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bMultiplication)
                            .addComponent(b6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b3)
                            .addComponent(bMinus))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(b0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bPlus)
                        .addComponent(bReboot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(bEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bForward))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        if(reboot)
            tFScreen.setText("");
        tFScreen.setText(tFScreen.getText()+"6");
        reboot = false;
    }//GEN-LAST:event_b6ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        if(reboot)
            tFScreen.setText("");
        tFScreen.setText(tFScreen.getText()+"0");
        reboot = false;
    }//GEN-LAST:event_b0ActionPerformed

    private void bForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bForwardActionPerformed
        // TODO add your handling code here:
        if(timer != null)
            if(timer.isRunning()==true){
                timer.stop();
                tAResultScreen.setText(machine.getMovements().get(machine.getMovements().size()-1)+"\n");
                tAResultScreen.append(machine.getMoves().get(machine.getMoves().size()-1)+"\n");
            }
    }//GEN-LAST:event_bForwardActionPerformed

    private void bRebootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRebootActionPerformed
        // TODO add your handling code here:
        tFScreen.setText("");
    }//GEN-LAST:event_bRebootActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if(reboot)
            tFScreen.setText("");
        tFScreen.setText(tFScreen.getText()+"1");
        reboot = false;
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(reboot)
            tFScreen.setText("");
        tFScreen.setText(tFScreen.getText()+"2");
        reboot = false;
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if(reboot)
            tFScreen.setText("");
        tFScreen.setText(tFScreen.getText()+"3");
        reboot = false;
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if(reboot)
            tFScreen.setText("");
        tFScreen.setText(tFScreen.getText()+"4");
        reboot = false;
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if(reboot)
            tFScreen.setText("");
        tFScreen.setText(tFScreen.getText()+"5");
        reboot = false;
    }//GEN-LAST:event_b5ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if(reboot)
            tFScreen.setText("");
        tFScreen.setText(tFScreen.getText()+"7");
        reboot = false;
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if(reboot)
            tFScreen.setText("");
        tFScreen.setText(tFScreen.getText()+"8");
        reboot = false;
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        if(reboot)
            tFScreen.setText("");
        tFScreen.setText(tFScreen.getText()+"9");
        reboot = false;
    }//GEN-LAST:event_b9ActionPerformed

    private void bDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivisionActionPerformed
        // TODO add your handling code here:
        if(!tFScreen.getText().equals("")){
            number1 = tFScreen.getText();
            logicOperator = "Dividir";
            tFScreen.setText(tFScreen.getText()+" / ");
            reboot=false;
        }
    }//GEN-LAST:event_bDivisionActionPerformed

    private void bMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMultiplicationActionPerformed
        // TODO add your handling code here:
          if(!tFScreen.getText().equals("")){
            number1 = tFScreen.getText();
            logicOperator = "Multiplicar";
            tFScreen.setText(tFScreen.getText()+" * ");
            reboot=false;
        }
    }//GEN-LAST:event_bMultiplicationActionPerformed

    private void bMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMinusActionPerformed
        // TODO add your handling code here:
        if(!tFScreen.getText().equals("")){
            number1 = tFScreen.getText();
            logicOperator = "Restar";
            tFScreen.setText(tFScreen.getText()+" - ");
            reboot=false;
        }
    }//GEN-LAST:event_bMinusActionPerformed

    private void bPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlusActionPerformed
        // TODO add your handling code here:
        if(!tFScreen.getText().equals("")){
            number1 = tFScreen.getText();
            logicOperator = "Sumar";
            tFScreen.setText(tFScreen.getText()+" + ");
            reboot=false;
        }
    }//GEN-LAST:event_bPlusActionPerformed

    private void bEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEqualActionPerformed
        // TODO add your handling code here:
        System.out.println();
        String aux = number1 +"   ";
        number2 = tFScreen.getText().substring(aux.length());
        if(number2.equals(""))
            number2="0";
        simulationBelt(number1, number2, logicOperator);
        reboot = true;
    }//GEN-LAST:event_bEqualActionPerformed

    private void tFScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFScreenActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        String Result;
        Result = tFScreen.getText();
        if(Result.length()> 0)
            Result = Result.substring(0, Result.length() -1);
            tFScreen.setText(Result);
        
    }//GEN-LAST:event_bClearActionPerformed
    
    public void simulationBelt(String number1, String number2, String logicOperator){
           try{
                 if(timer != null)
                if(timer.isRunning()==true)
                    timer.stop();
               machine.addBelt(Integer.parseInt(number1), Integer.parseInt(number2), logicOperator);
               
                 String texto =machine.getMovements().get(0) + "\n";
            tAResultScreen.setText(texto);

            texto =machine.getMoves().get(0) + "\n";
            tAResultScreen.append(texto);
            
             switch(logicOperator){

                case "Sumar":
                   tFScreen.setText(""+ machine.addition(Integer.parseInt(number1), Integer.parseInt(number2)));
                    break;

                case "Restar":
                    tFScreen.setText(""+ machine.subtraction(Integer.parseInt(number1), Integer.parseInt(number2)));
                    break;

                case "Multiplicar":
                    tFScreen.setText(""+ machine.multiplication(Integer.parseInt(number1), Integer.parseInt(number2)));
                    break;

                case "Dividir":
                    tFScreen.setText(""+ machine.division(Integer.parseInt(number1), Integer.parseInt(number2)));
                    break;    
            }
                 
 
           }
           catch(Exception e){
               System.err.println(""+e.getMessage());
               JOptionPane.showMessageDialog(null, ""+e.getMessage());
               tFScreen.setText("");
           }
      

            
             
            
ActionListener task = new ActionListener() {
                int x=1; 

                @Override
                public void actionPerformed(ActionEvent e){
                    
                     
                    if(x<machine.getMoves().size()){
                        String texto =machine.getMovements().get(x) + "\n";
                        tAResultScreen.setText(texto);
                        
                        texto =machine.getMoves().get(x) + "\n";
                        tAResultScreen.append(texto);
                    }else{
                        timer.stop();
                    }
                    x++;
                }   
            };
            
            timer = new Timer(delay,  task);
            timer.start(); 
        }

              
          
            
           
           

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorView().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDivision;
    private javax.swing.JButton bEqual;
    private javax.swing.JButton bForward;
    private javax.swing.JButton bMinus;
    private javax.swing.JButton bMultiplication;
    private javax.swing.JButton bPlus;
    private javax.swing.JButton bReboot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tAResultScreen;
    private javax.swing.JTextField tFScreen;
    // End of variables declaration//GEN-END:variables
}
